-- Tabla 
-- adempiere.amf_element_value_tree_cache definition
-- Drop table
-- DROP TABLE adempiere.amf_element_value_tree_cache;

CREATE TABLE adempiere.amf_element_value_tree_cache (
	ad_client_id numeric NOT NULL,
	c_acctschema_id numeric NOT NULL,
	"level" int4 NULL,
	node_id numeric NULL,
	parent_id numeric NULL,
	c_element_id numeric NULL,
	c_elementvalue_id numeric NULL,
	isactive bpchar(1) NULL,
	codigo varchar NULL,
	"name" varchar NULL,
	description text NULL,
	length int4 NULL,
	accounttype bpchar(1) NULL,
	accountsign bpchar(1) NULL,
	isdoccontrolled bpchar(1) NULL,
	issummary bpchar(1) NULL,
	acctparent _varchar NULL,
	pathel varchar NULL,
	ancestry _numeric NULL,
	codigo0 varchar NULL,
	name0 varchar NULL,
	description0 text NULL,
	issummary0 bpchar(1) NULL,
	codigo1 varchar NULL,
	name1 varchar NULL,
	description1 text NULL,
	issummary1 bpchar(1) NULL,
	codigo2 varchar NULL,
	name2 varchar NULL,
	description2 text NULL,
	issummary2 bpchar(1) NULL,
	codigo3 varchar NULL,
	name3 varchar NULL,
	description3 text NULL,
	issummary3 bpchar(1) NULL,
	codigo4 varchar NULL,
	name4 varchar NULL,
	description4 text NULL,
	issummary4 bpchar(1) NULL,
	codigo5 varchar NULL,
	name5 varchar NULL,
	description5 text NULL,
	issummary5 bpchar(1) NULL,
	codigo6 varchar NULL,
	name6 varchar NULL,
	description6 text NULL,
	issummary6 bpchar(1) NULL,
	codigo7 varchar NULL,
	name7 varchar NULL,
	description7 text NULL,
	issummary7 bpchar(1) NULL,
	codigo8 varchar NULL,
	name8 varchar NULL,
	description8 text NULL,
	issummary8 bpchar(1) NULL,
	codigo9 varchar NULL,
	name9 varchar NULL,
	description9 text NULL,
	issummary9 bpchar(1) NULL,
	created timestamp DEFAULT now() NULL
);


-- Query amf_element_value_tree_cache_refresh
-- Fill amf_element_value_tree_cache table with Function

INSERT INTO amf_element_value_tree_cache (
    ad_client_id,
    c_acctschema_id,
    level,
    node_id,
    parent_id,
    c_element_id,
    c_elementvalue_id,
    isactive,
    codigo,
    name,
    description,
    length,
    accounttype,
    accountsign,
    isdoccontrolled,
    issummary,
    acctparent,
    pathel,
    ancestry,
    codigo0,
    name0,
    description0,
    issummary0,
    codigo1,
    name1,
    description1,
    issummary1,
    codigo2,
    name2,
    description2,
    issummary2,
    codigo3,
    name3,
    description3,
    issummary3,
    codigo4,
    name4,
    description4,
    issummary4,
    codigo5,
    name5,
    description5,
    issummary5,
    codigo6,
    name6,
    description6,
    issummary6,
    codigo7,
    name7,
    description7,
    issummary7,
    codigo8,
    name8,
    description8,
    issummary8,
    codigo9,
    name9,
    description9,
    issummary9
)
SELECT
    $P{AD_Client_ID},
    $P{C_AcctSchema_ID},
    level,
    node_id,
    parent_id,
    c_element_id,
    c_elementvalue_id,
    isactive,
    codigo,
    name,
    description,
    length,
    accounttype,
    accountsign,
    isdoccontrolled,
    issummary,
    acctparent,
    pathel,
    ancestry,
    codigo0,
    name0,
    description0,
    issummary0,
    codigo1,
    name1,
    description1,
    issummary1,
    codigo2,
    name2,
    description2,
    issummary2,
    codigo3,
    name3,
    description3,
    issummary3,
    codigo4,
    name4,
    description4,
    issummary4,
    codigo5,
    name5,
    description5,
    issummary5,
    codigo6,
    name6,
    description6,
    issummary6,
    codigo7,
    name7,
    description7,
    issummary7,
    codigo8,
    name8,
    description8,
    issummary8,
    codigo9,
    name9,
    description9,
    issummary9
FROM amf_element_value_tree_extended(
    $P{AD_Client_ID},
    $P{C_AcctSchema_ID}
);


