source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               OSGI-INF/,\
               OSGI-INF/ModelFactory.xml,\
               OSGI-INF/EditorFactory.xml,\
               OSGI-INF/DisplayTypeFactory.xml,\
               OSGI-INF/EventFactory.xml,\
               OSGI-INF/AMXProcessFactory.xml,\
               OSGI-INF/AMXCalloutFactory.xml,\
               src/,\
               .,\
               plugin.xml

