-- ADEMPIERE.C_COMMUNITY definition

CREATE TABLE "ADEMPIERE"."C_COMMUNITY" 
   (	"C_COMMUNITY_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AD_CLIENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AD_ORG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ISACTIVE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CREATEDBY" NUMBER(10,0) NOT NULL ENABLE, 
	"UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATEDBY" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255 CHAR) DEFAULT NULL, 
	"C_COUNTRY_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ISDEFAULT" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"C_COMMUNITY_UU" VARCHAR2(36 CHAR) DEFAULT NULL, 
	 CONSTRAINT "C_COMMUNITY_KEY" PRIMARY KEY ("C_COMMUNITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CHECK (IsActive IN ('Y','N')) ENABLE, 
	 CHECK (IsDefault IN ('Y','N')) ENABLE, 
	 CONSTRAINT "C_COMMUNITY_UU_IDX" UNIQUE ("C_COMMUNITY_UU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "ADEMPIERE"."C_COMMUNITY_KEY" ON "ADEMPIERE"."C_COMMUNITY" ("C_COMMUNITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "ADEMPIERE"."C_COMMUNITY_UU_IDX" ON "ADEMPIERE"."C_COMMUNITY" ("C_COMMUNITY_UU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;